AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MySQSLambda
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: src/
      MemorySize: 2048
      Timeout: 900
      Architectures:
        - x86_64
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MySQSQueue.Arn
            BatchSize: 1

  MySQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MySQSQueue