# FFMPEG CONFIG
FFMPEG = 'ffmpeg'
MAX_NUMER_OF_THREADS = 10

# AWS CONFIG
AWS_REGION = 'us-east-1'
DYNAMO_TABLE_NAME = 'video-frames-control'

# ENV AUX
OUTPUT_FRAMES_DIR_NAME = 'temp_output_frames'
OUTPUT_DOWNLOAD_DIR_NAME = 'temp_download'
OUTPUT_ZIP_DIR_NAME = 'temp_zip'
ENCODE='utf-8'

# S3 CONFIG
BUCKET_NAME = 'video-processing-service'
RESULT_FOLDER_NAME = 'results'
DOWNLOAD_FOLDER_NAME = 'uploads'

# STATUS DYNAMODB
DYNAMO_STATUS_START_PROCESS='START_PROCESS'
DYNAMO_STATUS_DOWNLOAD_VIDEO_IN_PROGRESS= 'DOWNLOAD_VIDEO_IN_PROGRESS'
DYNAMO_STATUS_PROCESSING_CUT_FRAMES='PROCESSING_CUT_FRAMES'
DYNAMO_STATUS_ZIP_FILE_IN_PROGRESS='ZIP_FILE_IN_PROGRESS'
DYNAMO_STATUS_UPLOAD_RESULT_IN_PROGRESS = 'UPLOAD_RESULT_IN_PROGRESS'
DYNAMO_STATUS_ERROR='ERROR'
DYNAMO_STATUS_END_PROCESS='END_PROCESS'

